### ISSUE TITLE
[suggestion] Total Editor Time

### ISSUE THREAD

**Issue by Aktimoose** [TechStudent10/DiscordRPC#15]
When in an editor, the time elapsed should track the total amount of time spent in the editor for a level.

![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/ee2291cb-9e00-40e0-b45e-6e74a39507c0)
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/342f7526-fb65-40d9-861a-d5797d9ac42b)
they don't match but it would be so awesome .. it would be so cool

**Comment by TechStudent10** [comment]
The total editor time is shown beside the object count because getting Discord to display the editor time in the elapsed field was complex given the structure of the project.

**Comment by Aktimoose** [comment]
It would probably be better to have the time appear before the "worked on for" text, since it gets cut off usually. (Potentially `(3h 21h 53s Total Editor Time)`)
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/553f486a-1b29-4204-b43b-8c068beac22d)

**Comment by TechStudent10** [comment]
> It would probably be better to have the time appear before the "worked on for" text, since it gets cut off usually. (Potentially `(3h 21h 53s Total Editor Time)`) ![image](https://private-user-images.githubusercontent.com/44620677/317240995-553f486a-1b29-4204-b43b-8c068beac22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NjE4MzYsIm5iZiI6MTcxMTU2MTUzNiwicGF0aCI6Ii80NDYyMDY3Ny8zMTcyNDA5OTUtNTUzZjQ4NmEtMWIyOS00MjA0LWI0M2ItOGMwNjhiZWFjMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE3NDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDE0MTk4MTY1MDAxZmQ0ZmVlY2ZkNmI4OTg5ZWVhOWNkZjEyOWI1YTU5ZGMyNjQ1MDEyM2Y0YTNlMDM4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M8MzG3Gl1IaaQAevTjtXmTUSv-qczXW-7nqWpxeHaqA)

will do (I added this in last minute haha)
