### ISSUE TITLE
disable rich presence after gd is in background for some time

### ISSUE THREAD

**Issue by flurrybun** [TechStudent10/DiscordRPC#16]
since gd provides an easy way to tell if the game is currently in the foreground or background (by binding [applicationWillEnterForeground and applicationDidEnterBackground](https://docs.geode-sdk.org/classes/AppDelegate#applicationWillEnterForeground)), it would be nice to have an option to disable rich presence after being in the background for a customizable amount of time

sometimes i accidentally leave gd open overnight and my friends make fun of me for playing geometry dash at like 4 in the morning 💔

**Comment by TechStudent10** [comment]
such a relatable problem, will see if it's feasible to implement
