### ISSUE TITLE
another button button not working

### ISSUE THREAD

**Issue by InfernoZv** [TechStudent10/DiscordRPC#18]
oh yeah while I was messing around I found out that the shards button doesn't work also.
![image](https://github.com/TechStudent10/DiscordRPC/assets/164727301/0651c142-94cb-4b81-b53f-4df8afa94517)

**Comment by TechStudent10** [comment]
god @NetheriteMiner how many original function calls did you miss

(it's fine I'll add them all back)

**Comment by TechStudent10** [comment]
fixed in the latest commit
