### ISSUE TITLE
Idle status checkbox does nothing

### ISSUE THREAD

**Issue by Fryy55** [TechStudent10/DiscordRPC#19]
Title. Checking the "Show idle status" setting off does not prevent the mod from saying you're idling when unfocused

**Comment by TechStudent10** [comment]
What platform are you on?

**Comment by Fryy55** [comment]
PC, Windows 11

**Comment by TechStudent10** [comment]
Fixed in the latest commit (in other words, update DiscordRPC some minutes from now)

**Comment by Fryy55** [comment]
Now it's kinda even worse - it just says "idling" when show idle status is unchecked, so basically same thing just uncapitalized

**Comment by TechStudent10** [comment]
> Now it's kinda even worse - it just says "idling" when show idle status is unchecked, so basically same thing just uncapitalized

there's no way.

Are you sure you're on the latest version?

**Comment by Fryy55** [comment]
Version 2.10.1
![image](https://github.com/TechStudent10/DiscordRPC/assets/160249433/f9ec64a7-44d6-4199-b7ac-edef79910d10)

**Comment by TechStudent10** [comment]
Update to v2.10.2 and see if that fixes it

**Comment by Fryy55** [comment]
> Update to v2.10.2 and see if that fixes it

It does, you're the goat for actually investigating and fixing
