### ISSUE TITLE
Discord RPC not working after last patch

### ISSUE THREAD

**Issue by FL4MIN** [TechStudent10/DiscordRPC#24]
Discord RPC is not working anymore since yesterday Discord update.
The activity doesn't show at all, until yesterday it was fine.
Is it just me or it doesn't work anymore for anyone due to the new Discord patch? I believe the mod needs to be update.

Discord version: stable 292725 (485a03a) Host 1.0.9147 x64 (47834) Windows 11 64-bit (10.0.22631)

**Comment by TechStudent10** [comment]
I, nor others, have any success in replicating this error.

Have you tried updating Geode, DRPC, and Discord any further?

**Comment by FL4MIN** [comment]
No idea what caused it but the issue got fixed by itself yesterday after some Geode updates.
Thank you anyway!
