### ISSUE TITLE
this mod is not compatible with Geode v4.0.1

### ISSUE THREAD

**Issue by TimothyKuijper** [TechStudent10/DiscordRPC#27]
Is there gonna be an update for this more recent version of Geode?

**Comment by TechStudent10** [comment]
yes I will be updating all my mods soon

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/06e9cfcc-bd12-48a6-bfd1-18cbc94134e2)
temporary solution tho things MIGHT crash

**Comment by TechStudent10** [comment]
> ![image](https://github.com/user-attachments/assets/06e9cfcc-bd12-48a6-bfd1-18cbc94134e2)
> temporary solution tho things MIGHT crash

things WILL crash. I need to update the binary itself or else geode will not like it

**Comment by ghost** [comment]
> > ![image](https://private-user-images.githubusercontent.com/115172127/389645992-06e9cfcc-bd12-48a6-bfd1-18cbc94134e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTUxMTMsIm5iZiI6MTczMjkxNDgxMywicGF0aCI6Ii8xMTUxNzIxMjcvMzg5NjQ1OTkyLTA2ZTljZmNjLWJkMTItNDhhNi1iZmQxLTE4Y2JjOTQxMzRlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQyMTEzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTRmOWIwOTJmMWY4Mzg0OWU5YTFlMzM1YjE4OTJkNWEwNjc2NTlmZjI5NzAyNzhiNjVjMWU4NzAxMDFlMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OC7pDVZyKI1vLlXfiBWr6pnYHd5mqBRGA12XeTkPL0A)
> > temporary solution tho things MIGHT crash
> 
> things WILL crash. I need to update the binary itself or else geode will not like it

didn't seem to crash for me, but you did update it pretty quickly afterwards so thank you anyway 🔥

**Comment by TechStudent10** [comment]
correct, mod has been updated
