### ISSUE TITLE
mobile now!!!!

### ISSUE THREAD

**Issue by CatastrophicGD** [TechStudent10/DiscordRPC#3]
make it for mobile now!!!

**Comment by TechStudent10** [comment]
uh idk how to make mobile RPC so like

**Comment by TechStudent10** [comment]
Might do some research on it, but don't bet on it

**Comment by D4isDAVID** [comment]
I'm pretty sure that RPC for mobile isn't available at the moment.

Probably the only way right now to have rich presence from mobile is to use the gateway API, but that's just more complicated and also [breaks Discord's TOS](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots).

**Comment by TechStudent10** [comment]
> I'm pretty sure that RPC for mobile isn't available at the moment.
> 
> Probably the only way right now to have rich presence from mobile is to use the gateway API, but that's just more complicated and also [breaks Discord's TOS](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots).

Yeah this is correct. I was considering using the Gateway but have decided against it.
