### ISSUE TITLE
rich presence has some bugs

### ISSUE THREAD

**Issue by Zeirous** [TechStudent10/DiscordRPC#4]
---when you open a level at the menu it already starts the level in the RPC before actually playing the level, when playing the level the elapsed time disappeared as well too.---

if u can also add an indication if its a platformer with a star or a moon that would be awesome for the levels pls maybe more variety with levels like daily level. weekly level. gaunlet level,  and if level is rated or not

**Comment by TechStudent10** [comment]
> ---when you open a level at the menu it already starts the level in the RPC before actually playing the level, when playing the level the elapsed time disappeared as well too.---

Known bug, will fix.

> if u can also add an indication if its a platformer with a star or a moon that would be awesome for the levels pls maybe more variety with levels like daily level. weekly level. gaunlet level,  and if level is rated or not

You can actually tell if the level is rated by hovering over the difficulty icon, but I like the more variety idea.
