### ISSUE TITLE
daily not showing even though stated in update

### ISSUE THREAD

**Issue by Zeirous** [TechStudent10/DiscordRPC#5]
bug: in the update it said daily level was added but it does not work, another issue is that **after playing a level** you have go back all the way to main menu start to see browsing menus when it should say browsing menus or creator tab after you exit viewing the level

![image](https://github.com/TechStudent10/DiscordRPC/assets/84685318/d8c3f58f-4fa5-4650-917a-52b5b30950d3)

![image](https://github.com/TechStudent10/DiscordRPC/assets/84685318/7c68b229-2404-4b31-93d9-78752d2c4e0b)
![image](https://github.com/TechStudent10/DiscordRPC/assets/84685318/ac387c90-b253-4e6a-b2b1-8f61716f1b3d)

:future request --i also see that there were future plans to adding more variety like weekly, map packs or even lists and im glad you are seeing these ideas already! also btw robtop stated that all main level demons are easy demons not hard as shown in game but its up to u to decide what face u want. is there any plans for featured, epic, legendary, mythic rings for the icons?

**Comment by TechStudent10** [comment]
Can't seem to reproduce...

![image](https://github.com/TechStudent10/DiscordRPC/assets/76978184/79dade3c-2e17-4738-913e-2b9e36c4582a)

**Comment by Zeirous** [comment]
is there a way I can give you my file of the mod?

**Comment by TechStudent10** [comment]
> is there a way I can give you my file of the mod?

you _could_ attach it to a comment, but I'm already releasing a fix for some of the other issues. You can try it when the index accepts the update

**Comment by Zeirous** [comment]
[discordrich.zip](https://github.com/TechStudent10/DiscordRPC/files/14092702/discordrich.zip)
