### ISSUE TITLE
Playtesting your own unpublished levels shows the author as RobTopGames

### ISSUE THREAD

**Issue by sofabeddd** [TechStudent10/DiscordRPC#6]
![image](https://github.com/TechStudent10/DiscordRPC/assets/146020160/90337fb5-8267-4671-9b20-f050dc68a63d)

**Comment by TechStudent10** [comment]
I cannot reproduce this bug uhhh

**Comment by TechStudent10** [comment]
_taken from Discord_
![image](https://github.com/TechStudent10/DiscordRPC/assets/76978184/42d031ac-4be4-4d0e-82b2-9419a26595fe)

Fix should be available in the next update

**Comment by TechStudent10** [comment]
fixed as of https://github.com/TechStudent10/DiscordRPC/commit/ccceb8adb7c9c126602cc79c69ae47e1afe0f834
